# Generated by Django 5.1.5 on 2025-03-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project_link', models.URLField(blank=True, null=True)),
                ('client_review', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_description', models.TextField(blank=True, null=True)),
                ('client_profile_link', models.URLField(blank=True, null=True)),
                ('client_portfolio_pic', models.ImageField(blank=True, null=True, upload_to='client_portfolios/')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='home.category')),
            ],
        ),
    ]
