# Generated by Django 5.1.5 on 2025-05-06 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profilecategory_profilecontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.RemoveField(
            model_name='profilecontent',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProfileCategory',
        ),
        migrations.DeleteModel(
            name='ProfileContent',
        ),
    ]
